# Generated by Django 3.1.7 on 2021-06-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job',
            field=models.CharField(choices=[('S', '학생'), ('O', '직장인'), ('F', '프리랜서'), ('E', '기타(Etc.)')], default='', max_length=1, verbose_name='직업'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', '남성(Male)'), ('F', '여성(Female))')], default='', max_length=1, verbose_name='성별'),
        ),
    ]
